### PR TITLE
Cut release v0.11.2

### PR DESCRIPTION
**Pull request by jaybooth4**
This release would address several critical CVEs fixed as part of a golang upgrade performed in https://github.com/kubernetes-sigs/prometheus-adapter/pull/606

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by jaybooth4** [comment]
@dgrisonnet can you take a quick look at this one when you get a chance? 🙌

**Review by dgrisonnet — APPROVED** [review]
I am at KubeCon right now so I'll not have time to publish the tag and images until Friday.

/lgtm
/approve

**Pull request merged**
