### PR TITLE
Add docs on helm installation

### PR DESCRIPTION
**Pull request by tomkerkhove**
Add docs on helm installation in README.

Relates to #12 #90

### CODE REVIEW

**Comment by DirectXMan12** [comment]
So, I'd prefer to just have a link to the helm chart -- I don't necessarily want people to be filing bugs about the helm chart here, since it'll be hard for me to support them.  I'm happy to link to it, but it's not the "official" supported installation method for the moment (the official supported installation method is `kubectl create -f deploy/manifests`).

However, I'm open to count-arguments on this matter :-).

**Comment by DirectXMan12** [comment]
Yeah, that link is perfect.  Maybe say something like

> If you're a helm user, a helm chart is listed on the Kubeapps Hub as [stable/prometheus-adapter](https://hub.kubeapps.com/charts/stable/prometheus-adapter)

or something (personally, I'm not a huge helm fan, but I understand why people like it :-) )

**Comment by tomkerkhove** [comment]
Sounds good to me! Do you prefer to have only that one-liner or just adapt current phrasing?

Ha, that's interesting - Probably because you prefer to know the details/advanced stuff?

**Comment by DirectXMan12** [comment]
> Probably because you prefer to know the details/advanced stuff?

Yeah, a bit.  There's a few reasons -- I'm not a huge fan of the tiller architecture, but beyond that, I think it's at least partially the wrong abstraction, at least for me.  It's great if you only have one or two knobs, but once you have a bunch of knobs, you end up with a second complicated layer on top of the kubernetes YAML that mirrors a lot of the Kubernetes YAML, only slightly differently.  It also means that you don't get used to how Kubernetes objects actually look, which means that when you go to debug your cluster, you've got a completely different "language" (kubernetes YAML) than the what you normally use (per-chart helm yaml), and you've got less of an idea as to what's actually going on.  Furthermore, if you already know Kubernetes, you have to re-learn where particular knobs are in any given Helm chart.

I very much prefer the approach [kustomize](https://github.com/kubernetes-sigs/kustomize) took -- you still work with kubernetes objects, and customization is done by layering patches on top, plus some basic primatives for pulling files into secrets and configmaps.  This means that you still interact with snippets of Kubernetes YAML (to make the patches), and you can customize any knob in the underlying Kubernetes object, but because they're patches, they're still relatively small and easy to read.

That's not to say that I don't sympathize with what Helm is trying to do -- customizing Kubernetes objects, and packing that for deployment, can be crazy complicated for a newcomer.

**Comment by DirectXMan12** [comment]
>  Do you prefer to have only that one-liner or just adapt current phrasing?

The one liner is fine, but if you've got better wording, feel free to use that -- that was just off the top of my head.

**Comment by tomkerkhove** [comment]
@DirectXMan12 I've updated it and think this looks ok. Feel free to let me know if you agree.

**Comment by tomkerkhove** [comment]
Thanks for considering, reviewing and merging this PR8

**Pull request merged**
