### PR TITLE
Fix external rule tag in documentation

### PR DESCRIPTION
**Pull request by ashishranjan1457**
Replaced external: by externalRules: in documentation for external rules

### CODE REVIEW

**Comment by dgrisonnet** [comment]
@ashishranjan1457 would you mind also updating the [sample-config.yaml](https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/sample-config.yaml#L70)?

**Comment by ashishranjan1457** [comment]
> @ashishranjan1457 would you mind also updating the [sample-config.yaml](https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/sample-config.yaml#L70)?

done

**Comment by dgrisonnet** [comment]
Awesome, thank you!

/lgtm
/approve

**Pull request merged**
