### PR TITLE
Bump to Kubernetes 1.30

### PR DESCRIPTION
**Pull request by dgrisonnet**
Bump all the dependencies, custom-metrics-apiserver and Kubenetes to 1.30.

Since there is no kind image available for 1.30 yet, I built one myself and use it in the tests. I will change that later once an official image is available.

### CODE REVIEW

**Comment by dgrisonnet** [comment]
cc @jaybooth4

**Comment by CatherineF-dev** [comment]
Regarding version skew, could users deploy prometheus-adapter 1.30 in cluster k8s 1.28?

**Comment by dgrisonnet** [comment]
There is an odd issue with the linter, I'll investigate. I'll look at the e2e tests later

**Comment by chc5** [comment]
Any updates here? I'd like to get these upgrades submitted to address vulnerabilities in this project.

**Comment by dgrisonnet** [comment]
If you are talking about the otel CVE, the project is not affected. That said, I'll be looking at this PR again soon.

**Pull request merged**
