### PR TITLE
Update documentation to include metrics-max-age

### PR DESCRIPTION
**Pull request by leoskyrocker**

### CODE REVIEW

**Comment by s-urbaniak** [comment]
cc @dgrisonnet

**Comment by dgrisonnet** [comment]
Thank you for the awesome addition @leoskyrocker! :100: 

/check-cla
/ok-to-test

**Comment by dgrisonnet** [comment]
@leoskyrocker if you have signed the CLA, can you please check if your commit is authored with the same email address as the one you signed the CLA with?

**Comment by leoskyrocker** [comment]
Sorry haven't been able to get it to send a hellosign email to me so far (I've tried to amend my commit with the correct email previously). I've pick this back up once I have some time for it (in a few days).

**Comment by leoskyrocker** [comment]
@dgrisonnet seems all good now!

**Comment by dgrisonnet** [comment]
Awesome, thank you @leoskyrocker.

/lgtm
/approve

**Pull request merged**
