### PR TITLE
*: add version file

### PR DESCRIPTION
**Pull request by paulfantom**
VERSION file is an easy way to determine the version in various automation scenarios (for example in Makefile).

/cc @dgrisonnet 

Signed-off-by: paulfantom <pawel@krupa.net.pl>

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Would you mind also updating https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/.travis-deploy.sh to differentiate between deployments of release and latest images?

**Comment by paulfantom** [comment]
Updated travis script, but I am not 100% sure this is the correct way. @dgrisonnet could you double-check?

**Pull request merged**
