### PR TITLE
Cut release v0.11.2

### PR DESCRIPTION
**Pull request by jaybooth4**
This release would address several critical CVEs fixed as part of a golang upgrade performed in https://github.com/kubernetes-sigs/prometheus-adapter/pull/606

### CODE REVIEW

**Comment by jaybooth4** [comment]
Hi @dgrisonnet, are we able to merge this CL to release a new version that addresses the open CVEs?

**Comment by dgrisonnet** [comment]
@jaybooth4 sorry for the delay. Could you perhaps backport https://github.com/kubernetes-sigs/prometheus-adapter/pull/606 to release-0.11, and open this PR against the release branch as well as master?

I noticed that I incorrectly cut v0.11.1 out of master, but it should've been on release-0.11. I synced the release branch with https://github.com/kubernetes-sigs/prometheus-adapter/pull/613 so it should be good now.

**Comment by jaybooth4** [comment]
Hey [dgrisonnet](https://github.com/dgrisonnet), PTAL

https://github.com/kubernetes-sigs/prometheus-adapter/pull/617

https://github.com/kubernetes-sigs/prometheus-adapter/pull/616

Thank you!

**Comment by jaybooth4** [comment]
This CL was merged instead: https://github.com/kubernetes-sigs/prometheus-adapter/pull/617

**Comment by dgrisonnet** [comment]
Both PRs need to be merged, but this one post release so that users can have manifests pointing to the latest release on master

**Review by dgrisonnet — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
