### PR TITLE
Patch upgrade of Golang to 1.18.9

### PR DESCRIPTION
**Pull request by gburton1**
Signed-off-by: Greg Burton <9094087+gburton1@users.noreply.github.com>

Should fix https://github.com/kubernetes-sigs/prometheus-adapter/issues/541

### CODE REVIEW

**Comment by olivierlemasle** [comment]
Thank you @gburton1

/triage accepted
/ok-to-test
/lgtm
/assign @dgrisonnet

**Comment by olivierlemasle** [comment]
A new release will still be required to fix #541.

**Comment by gburton1** [comment]
Thank you...yes, cutting a release after merging this would be great because the last version was cut in August and has overdue CVEs now.

**Pull request merged**
