### PR TITLE
Fix broken links in README.md

### PR DESCRIPTION
**Pull request by sillyfrog**
Minor issue, fixes a few broken links to the (now finalized) Metrics APIs.

### CODE REVIEW

**Review by olivierlemasle — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by dgrisonnet** [comment]
Sorry I missed this PR.

Thank you for sending the fix @sillyfrog, would you mind squashing the commits into one?

**Comment by sillyfrog** [comment]
@dgrisonnet That's done, made a bit of a mess of it, but I've just re-applied the patch on the current master. Please let me know if there's anything else you need.

Cheers.

**Comment by dgrisonnet** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
