### PR TITLE
Cut release 0.11.3

### PR DESCRIPTION
**Pull request by jaybooth4**
Getting release changes ready to make it easy to cut a new version 👍

### CODE REVIEW

**Comment by dgrisonnet** [comment]
@jaybooth4 do you specifically need a patch version?

I was considering cutting 0.12.0 based on Kubernetes 1.30 since Kubernetes 1.27 that 0.11 is based on is not supported anymore.

I can cut it tomorrow as long as https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/172 goes in

**Comment by jaybooth4** [comment]
Hey @dgrisonnet, no that sounds good! Let me know if you'd like any CLs around cutting a new release 👍

**Comment by chc5** [comment]
Are there any updates here? 

@dgrisonnet Since https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/172 was merged, do you want to review the following change here?

**Comment by dgrisonnet** [comment]
Superseded by https://github.com/kubernetes-sigs/prometheus-adapter/pull/659.

I'll work on the 0.12.0 release now.

**Pull request closed without merging**
